apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test
spec:
  containers:
  - name: test
    image: diegoguerreroborda/test:latest
    ports:
      - containerPort: 5000


# kubectl apply -f .\k8s\pod.yaml
# kubectl get pods

# kubectl logs test-pod